### ISSUE TITLE
ccr -Si will only show pkgs from official repo if ccr and official repo both have the same pkgs

### ISSUE THREAD

**Issue by s8321414** [ccr-tools/ccr-tools#37]
As title says, ccr -Si will **only** show pkgs from official repo if CCR and official repo **both** have same name pkgs.

**Comment by rshipp** [comment]
I don't think we need to support duplicate packages, since that's against the rules of the CCR. Whenever we find duplicates, they should be removed from the CCR.

**Comment by s8321414** [comment]
@rshipp so you think this issue is invalid?

**Comment by rshipp** [comment]
I would say so, yeah. We can use [ccrdups](https://github.com/ccr-tools/misc-ccr-tools/blob/master/ccrdups) to check for duplicates.
